name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: ./14-Exam-Preparation-Resources/package-lock.json
    - name: Run npm install
      run: |
        cd ./14-Exam-Preparation-Resources/
        npm install
    - name: Run unit tests
      run: |
        cd ./14-Exam-Preparation-Resources/
        npm run test:unit
    - name: Display name
      run: echo "KristiyqnPisev"
  
  build_ui_tests:
      runs-on: ubuntu-latest
      needs: build_unit_tests

      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: ./14-Exam-Preparation-Resources/package-lock.json
      - name: Run npm install
        run: |
          cd ./14-Exam-Preparation-Resources/
          npm install
      - name: Install playwright brousers
        run: npm playwright install
      - name: Start the app
        run: npm start &
      - name: Run ui tests
        run: |
          cd ./14-Exam-Preparation-Resources/
          npm run test:ui

